version: "3.6"
services:
  neocracy-db:
    container_name: neocracy-db
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neocracydb
      MYSQL_USER: user
      MYSQL_PASSWORD: neocracy
    networks:
      - neocracy

  neocracy-myadmin:
    container_name: neocracy-myadmin
    image: phpmyadmin
    restart: always
    depends_on:
      - neocracy-db
    links:
      - neocracy-db
    ports:
      - 8081:80
    environment:
      PMA_HOST: neocracy-db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - neocracy
      - web

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.1.1
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    networks:
      - web

networks:
  neocracy:
    name: neocracy
  web:
    name: web
